[features]
seeds = true
skip-lint = false

[programs.localnet]
signito_vault = "5gbaenRHg2YK6X8WMMQZevD55bJ7fvr4V8E8e1feDt5D"

[programs.devnet]
signito_vault = "5gbaenRHg2YK6X8WMMQZevD55bJ7fvr4V8E8e1feDt5D"

[programs.mainnet]
signito_vault = "CZBvErdLT8HL2iJS9NrRn7PhdeFWKNcMmvweEPsSbAAX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/runner/workspace/programs/deployer-keypair.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["signito-vault"]
